apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-first-deployment
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1 
      maxSurge: 20%
  replicas: 3
  selector: 
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: app
        image: docker.io/library/my-first-app:v1
        resources:
          requests:
            cpu: 500m
            memory: 64Mi
          limits:
            cpu: 1
            memory: 128Mi
        livenessProbe:
          httpGet:
            path: /
            port: 5000
          failureThreshold: 1
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 5000
          failureThreshold: 3
          periodSeconds: 5
          initialDelaySeconds: 20